# Generated by Django 4.2.1 on 2023-05-23 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accountminus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                ("amount", models.PositiveIntegerField(default=1, verbose_name="수량")),
                (
                    "minus_money",
                    models.PositiveIntegerField(default=0, verbose_name="지출금액단가"),
                ),
                (
                    "placename",
                    models.CharField(default="", max_length=50, verbose_name="매장 이름"),
                ),
                (
                    "placewhere",
                    models.CharField(default="", max_length=70, verbose_name="매장주소"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Accountplus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                (
                    "plus_money",
                    models.PositiveIntegerField(default=0, verbose_name="저축액"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challenge_title",
                    models.CharField(max_length=50, verbose_name="챌린지명"),
                ),
                ("challenge_content", models.TextField(verbose_name="내용")),
                ("amount", models.IntegerField(verbose_name="목표 금액")),
                ("period", models.CharField(max_length=10, verbose_name="목표 기간")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시간"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChallengeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="media/no_image.jpg",
                        null=True,
                        upload_to="challenge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsumeStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style", models.CharField(max_length=32, verbose_name="소비경향")),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "income_money",
                    models.PositiveIntegerField(default=0, verbose_name="지출금액단가"),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
            ],
        ),
    ]
