# Generated by Django 4.2.1 on 2023-05-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountminus",
            name="challenge",
        ),
    ]
